sources:
  auth_log:
      type: file
      include:
        - "/var/log/auth.log"

sinks:
  auth_log:
    type: loki
    inputs:
      - "auth_log"
    endpoint: "http://loki:3100"
    labels:
      job: "auth_log"
      log_path: "/var/log/auth_log"
      host: "{{ host }}"
      level: "{{ level }}"
    encoding:
      codec: json